### PR TITLE
[GraphiteWriter] Add support for TLS/SSL for TCP connections

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[GraphiteWriter] Add support for TLS/SSL for TCP connections and add … a `tlsInsecure` flag to support invalid x509 certificates (server Root CA not trusted by the client, expired cert ...)

### CODE REVIEW

**Comment by YannRobert** [comment]
Hey @cyrille-leclerc 
As I said on PR #96 it'd be interesting to follow this path.

Please consider PR #102 for implementation change proposal.

I still have to test this in my applications. i'll keep you posted.

**Comment by cyrille-leclerc** [comment]
Hello @YannRobert, I added the support for custom trust store and key store so that people can safely handle self signed X509 certificates or certificate authorities not bundled in their JVM.

Do you see use cases where people would have to declare their own SSLSocketFactory if not to weaken X509 certificate checks or to declare self-signed certs or Certificate Authorities that are not bundled by the JVM?

Cyrille

**Comment by YannRobert** [comment]
I like to use a custom HostnameVerifier that checks the SSLSession after handshake is really secure.
Typically, I want the client and server negotiate a TLS 1.2 session with a safe Cipher Suite (not known as vulnerable)
My custom HostnameVerifier returns false when the Cipher Suite is vulnerable or weak.

There is an other orthogonal way to do that (jdk.tls.disabledAlgorithms), although not as flexible. 
Using a HostnameVerifier I can
- log interesting properties so that I know what's wrong
- use a different security level, depending on the service being called (for instance www.googleapis.com works with TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 but I generally require a higher level for other services)

The fact that jmxtrans is generally not allowing dependency injection would require that it allows a wide set of properties (in the jmxtrans.json file) to customize the SocketFactory.

Because it's hard to think of all usecases upfront, that why I proposed a Factory interface that would be loaded from the application classpath, that would eventually provide the customized Socket Factory

Interestingly, when the application is already using Apache HC, it constructs a org.apache.http.conn.ssl.SSLConnectionSocketFactory with the javax.net.ssl.SSLContext and the javax.net.ssl.HostnameVerifier.
And the SSLConnectionSocketFactory can be used to create the Socket.

That why I suggest that : 
- jmxtrans keeps it simple, as you did with the first commit, just providing a way to use tls, eventually accepting all insecure connections => do it in this first PR
- on that, we has a Factory interface that can be implemented by the application, and if jmxtrans is provided the FQCN as a property, it then loads this class, and use it to create a Socket => do it in a different PR?

That would introduce some kind of """dependency injection""" in embedded-jmstrans. Now that's a design decision to allow that or not. What's your thought on this?

At some point, I thought of providing Dependency Injection at the EmbeddedJmxTransBeanDefinitionParser level. That's something to consider too.

**Comment by cyrille-leclerc** [comment]
@YannRobert I added the capability to specify a custom SocketFactory. This will allow people who want to do more than standard TLS to do it.

I did not add smart dependency injection as it would require to refactor the whole library. This can be discussed for jmxtrans2.

I did test the Graphite writers (TCP, TCP+TLS and UDP) on HostedGraphite.

I am confused with the HostnameVerifier as my understanding is that it only applies to HTTPS and not to tcp sockets, I don't think it is used to validate the TLS/SSL socket.

Cyrille

**Comment by YannRobert** [comment]
@cyrille-leclerc 
this PR do not build since the first commit
you may want to consider #102 so that it builds on java 6, 7, 8.
also, in subsequent commits, you have tests that fail
you may want to consider #103 to exclude the integration test from the default build

also, having to create multiple config files to make tests pass is overly complicated IMO. A default config file pointing to localhost and reasonable defaults should be sufficient? it would be overridden only if needed.

**Comment by cyrille-leclerc** [comment]
Thanks @YannRobert, I did not test on JDK 7 & 6.

I fixed the backward compatibility issue https://github.com/jmxtrans/embedded-jmxtrans/commit/fc4ca56f1b7c6a04fd8699a91b3b1d0b11618349

and setup CI with the 3 JDKs: https://jmxtrans.ci.cloudbees.com/

Regarding the multiple config files, it was a tradeoff between reusing the same config param names (e.g. host, port, protocol) and thus splitting the config in 3 files or prefixing the config param names (e.g. tcp_no_tls.port, tcp_tls_port, udp.port...). I chose the former but I admit that it has drawbacks.

**Comment by YannRobert** [comment]
```
For a test with Graphite over TLS with a trusted certificate, I did not expect people to have it locally and thus did not default to localhost. 
```
Maybe you can just try with hostedgraphite as a reasonable default value? Using an invalid API key or even not API key, it does not matter (hostedgraphite will discard it gracefully), when you just want to test SSL with a trusted certificate.

**Pull request merged**
