### PR TITLE
Fix AbstractOutputWriter toString()

### PR DESCRIPTION
**Pull request by YannRobert**
when calling toString() on an OutputWriter 

we expect "org.jmxtrans.embedded.output...."
but we get "class org.jmxtrans.embedded.output...."

this change fixes the issue

### CODE REVIEW

**Comment by YannRobert** [comment]
I just rebased the branch with jmxtrans:master
GH web UI does not refresh the changeset accordingly :crying_cat_face:

**Comment by YannRobert** [comment]
maybe the PR needs to be reopened so that GH refresh the changeset?

@cyrille-leclerc why did you close this PR without a merge ?

**Comment by cyrille-leclerc** [comment]
@YannRobert the horrible force-push automatically closed the PR. I recreated it at https://github.com/jmxtrans/embedded-jmxtrans/pull/111

I am sorry for this mess.

**Comment by YannRobert** [comment]
ok so all those PR were automatically closed with the force push on master? that's tragic :fearful: 
Can't you manually reopen? I can't. Will I have to recreate all of my pending PR?

**Comment by YannRobert** [comment]
merged by #117

**Pull request closed without merging**
